version: '3'

services:

  web:
    build:
      context: .
      dockerfile: dev.dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "80:80"
    env_file:
      - .env
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "80"]